rm -rf /mnt/lvsdb/*
rm -rf /mnt/lvsdc/*
rm -rf /mnt/lvsdd/*
rm -rf /mnt/lvsde/*
rm -rf /mnt/lvsdf/*
rm -rf /mnt/lvsdg/*
rm -rf /mnt/lvsdh/*
rm -rf /mnt/CVFSFStorage/*
rm -rf /mnt/CVFSTemp/*
rm -rf /mnt/Share/*
rm -rf /mnt/CVFSCache/*
rm -rf /mnt/CVFStorage/*
